### ISSUE TITLE
Scorm compliant

### ISSUE THREAD

**Issue by sureshmariadass** [SamirMoustafa/SoftwareProject#1]
this have scorm compliant ??

**Comment by SamirMoustafa** [comment]
> this have scorm compliant ??

Yes, where the professors can upload online training materials that can be shared across systems.

**Comment by sureshmariadass** [comment]
Can we upload a Scorm package ?

**Comment by SamirMoustafa** [comment]
@sureshmariadass yes, but we can't open it on the website, must download then open it...
